name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    
    container: cypress/included:4.11.0
    steps:
      - uses: actions/checkout@v2.4.2
      - run: npm install
      - run: npm start &
      
      - uses: actions/checkout@v2.4.2
        with: 
         repository: rmhiguerey/cypress
      
      - name: Install dependencies 📦
        uses: bahmutov/npm-install@v1

      - run: npx browserslist@latest --update-db
      - run: cypress run
  
