name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    container: cypress/included:4.11.0
    steps:
    - uses: actions/checkout@v2.4.2
    - run: npm install
    - run: npm start &
    #- run: curl --fail --request GET  --url "http://localhost:8080"

    - uses: actions/checkout@v2.4.2
      with: 
       repository: rmhiguerey/cypress
    - run: cypress run
